services:
  mariadb:
    container_name: mariadb
    image: mariadb
    networks:
      - inception
    build:
      context: requirements/mariadb
      dockerfile: Dockerfile
    env_file: .env
    secrets:
      - db_root_password
      - db_password
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: always
    expose:
      - "3306"

  wordpress:
    container_name: wordpress
    image: wordpress
    env_file: .env
    secrets:
      - db_password
      - wp_adm_user
      - wp_adm_mail
      - wp_adm_password
      - wp_guest_user
      - wp_guest_mail
      - wp_guest_password
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    build:
      context: requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - mariadb
    restart: always
    expose:
      - "9000"

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    depends_on:
      - wordpress
    build:
      context: requirements/nginx
      dockerfile: Dockerfile
    env_file: .env
    restart: always
    ports:
      - "443:443"

volumes:
  wordpress_data:
    name: wordpress_data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/chrhu/data/wordpress'
  mariadb_data:
    name: mariadb_data
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/chrhu/data/mariadb'
  
networks:
  inception:
    name: "inception"
    driver: "bridge"

secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt

  wp_adm_user:
    file: ../secrets/wp_adm_user.txt
  wp_adm_mail:
    file: ../secrets/wp_adm_mail.txt
  wp_adm_password:
    file: ../secrets/wp_adm_password.txt

  wp_guest_user:
    file: ../secrets/wp_guest_user.txt
  wp_guest_mail:
    file: ../secrets/wp_guest_mail.txt
  wp_guest_password:
    file: ../secrets/wp_guest_password.txt
